name: Build test

on:
  push:
    branches: [ "main", "fix_workflow" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses
        
      - name: Install SDK Components
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"
          
      - name: Set ANDROID_HOME
        run: echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Install ninja
        run: sudo apt-get update && sudo apt-get install ninja-build
        
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.31.1'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Building project
        run: ./gradlew assembleDebug --no-daemon
        
      # [修复] 升级到 v4 版本
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ github.run_number }}
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/**/*.aar
            **/build/intermediates/cmake/**/obj/**/*.so
          retention-days: 5
          if-no-files-found: warn